### PR TITLE
Fix unpinning bugs

### LINKED ISSUE #136: List does not revert to the previous sorting order after unpinning

### LINKED ISSUE #166: [PE-D][Tester B] Client list not updated after unpinned
Clients number 5 is still on the top of the list after unpinned

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: eesung00/ped#8

### LINKED ISSUE #187: [PE-D][Tester F] No ability to unpin projects, clients or issues
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zylee348/ped#7

### PR DESCRIPTION
**Pull request by ConradLew**
Fixes #136 , Fixes #166 , Fixes #187 .

### CODE REVIEW

**Review by Donovan9617 — APPROVED** [review]

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -359,4 +359,19 @@ public void sortIssuesByPin() {
         addressBook.sortIssuesByPin();
         updateFilteredIssueList(PREDICATE_SHOW_ALL_ISSUES);
     }
+
+    @Override
+    public void sortProjectsByCurrentCategory() {
+        addressBook.sortProjectsByCurrentCategory();
```
Comment (Donovan9617) [inline src/main/java/seedu/address/model/ModelManager.java:365]: Should maybe use "project book" instead of "address book"
